set( APPLICATION_NAME       "Prelive HiDrive Next" )
set( APPLICATION_SHORTNAME  "PreliveHiDriveNext" )
set( APPLICATION_EXECUTABLE "prelive-hidrive-next" )
set( APPLICATION_CONFIG_NAME "prelive-hidrive-next" )
set( LINUX_APPLICATION_ID "fr.ionos.storage.prelive.prelive-hidrive-next" )
set( APPLICATION_DOMAIN     "prelive.storage.ionos.fr" )
set( APPLICATION_VENDOR     "Ionos" )
set( APPLICATION_UPDATE_URL "https://customerupdates.nextcloud.com/client/" CACHE string "URL for updater" )
set( APPLICATION_HELP_URL   "https://wl.hidrive.com/easy/0118" CACHE string "URL for the help menu" )
set( APPLICATION_ICON_NAME  "Nextcloud" )
set( APPLICATION_ICON_SET  "SVG" )
set( APPLICATION_SERVER_URL [=[https://prelive.storage.ionos.fr]=] CACHE string "URL for the server to use. If entered the server can only connect to this instance" )
set( APPLICATION_SERVER_URL_ENFORCE ON )
set( DO_NOT_USE_PROXY OFF )
set( DISABLE_ACCOUNT_MIGRATION ON )
set( LINUX_PACKAGE_SHORTNAME "prelive-hidrive-next" )
set( THEME_CLASS            "NextcloudTheme" )
set( APPLICATION_REV_DOMAIN "fr.ionos.storage.prelive" )
set( WIN_SETUP_BITMAP_PATH  "${CMAKE_SOURCE_DIR}/admin/win/nsi" )
set( MAC_INSTALLER_BACKGROUND_FILE "${CMAKE_SOURCE_DIR}/admin/osx/installer-background.png" CACHE STRING "The MacOSX installer background image")
option( WITH_CRASHREPORTER "Build crashreporter" OFF )
option( WITH_PROVIDERS "Build with providers list" OFF )
option( BUILD_UPDATER "Build with updater" ON )
set( NEXTCLOUD_BACKGROUND_COLOR "#0077c2" CACHE string "Hex color of the wizard header background")
set( APPLICATION_WIZARD_HEADER_BACKGROUND_COLOR "#0077c2" CACHE string "Hex color of the wizard header background")
set( APPLICATION_WIZARD_HEADER_TITLE_COLOR "#001b41" CACHE string "Hex color of the text in the wizard header")
option( APPLICATION_WIZARD_USE_CUSTOM_LOGO "Use the logo from ':/client/theme/colored/wizard_logo.png' else the default application icon is used" ON )
set(ENCRYPTION_HARDWARE_TOKEN_DRIVER_PATH {})
set (CLIENTSIDEENCRYPTION_ENFORCE_USB_TOKEN false)
set( APPLICATION_DISPLAY_LEGACY_IMPORT_DIALOG OFF )
option(ENFORCE_SINGLE_ACCOUNT "Enforce use of a single account in desktop client" OFF)
