set( APPLICATION_NAME       "IONOS HiDrive Next" )
set( APPLICATION_SHORTNAME  "IONOSHiDriveNext" )
set( APPLICATION_EXECUTABLE "ionos_hidrive_next" )
set( APPLICATION_CONFIG_NAME "ionos_hidrive_next" )
set( APPLICATION_CONFIG_NAME "ionos-hidrive-next" )
set( LINUX_APPLICATION_ID "com.ionos.ionos_hidrive_next" )
set( APPLICATION_DOMAIN     "nextcloud-aio.iocaste45.de" )
set( APPLICATION_VENDOR     "Ionos" )
set( APPLICATION_UPDATE_URL "https://customerupdates.nextcloud.com/client/" CACHE string "URL for updater" )
set( APPLICATION_HELP_URL   "https://help.ionos.de" CACHE string "URL for the help menu" )
set( APPLICATION_ICON_NAME  "ionos_hidrive_next" )
set( APPLICATION_ICON_SET  "SVG" )
set( APPLICATION_SERVER_URL [=[https://nextcloud-aio.iocaste45.de]=] CACHE string "URL for the server to use. If entered the server can only connect to this instance" )
set( APPLICATION_SERVER_URL_ENFORCE ON )
set( DO_NOT_USE_PROXY ON )
set( LINUX_PACKAGE_SHORTNAME "ionos_hidrive_next" )
set( THEME_CLASS            "NextcloudTheme" )
set( APPLICATION_REV_DOMAIN "com.ionos" )
set( WIN_SETUP_BITMAP_PATH  "${CMAKE_SOURCE_DIR}/admin/win/nsi" )
set( MAC_INSTALLER_BACKGROUND_FILE "${CMAKE_SOURCE_DIR}/admin/osx/installer-background.png" CACHE STRING "The MacOSX installer background image")
option( WITH_CRASHREPORTER "Build crashreporter" OFF )
option( WITH_PROVIDERS "Build with providers list" OFF )
option( BUILD_UPDATER "Build with updater" ON )
set( NEXTCLOUD_BACKGROUND_COLOR "#05ff22" CACHE string "Hex color of the wizard header background")
set( APPLICATION_WIZARD_HEADER_BACKGROUND_COLOR "#05ff22" CACHE string "Hex color of the wizard header background")
set( APPLICATION_WIZARD_HEADER_TITLE_COLOR "#2a27b4" CACHE string "Hex color of the text in the wizard header")
option( APPLICATION_WIZARD_USE_CUSTOM_LOGO "Use the logo from ':/client/theme/colored/wizard_logo.png' else the default application icon is used" ON )
set(ENCRYPTION_HARDWARE_TOKEN_DRIVER_PATH {})
set (CLIENTSIDEENCRYPTION_ENFORCE_USB_TOKEN false)
option( ENFORCE_VIRTUAL_FILES_SYNC_FOLDER "Enforce use of virtual files sync folder when available" OFF )
set( APPLICATION_DISPLAY_LEGACY_IMPORT_DIALOG OFF )
option(ENFORCE_SINGLE_ACCOUNT "Enforce use of a single account in desktop client" ON)
set( WIN_SHELLEXT_CONTEXT_MENU_GUID      "{6B16FF7B-F242-4CE3-8FB9-F06EF127E0DC}" )
set( WIN_SHELLEXT_OVERLAY_GUID_ERROR     "{243D887B-9F74-41DD-BACA-BC5501AF10AC}" )
set( WIN_SHELLEXT_OVERLAY_GUID_OK        "{2D88D499-3272-4A76-84BF-D252254B40D6}" )
set( WIN_SHELLEXT_OVERLAY_GUID_OK_SHARED "{7BEF6B56-5B5B-4284-A70C-56D62254C97A}" )
set( WIN_SHELLEXT_OVERLAY_GUID_SYNC      "{5F2F493D-A683-426F-925E-4CA25F17C4A9}" )
set( WIN_SHELLEXT_OVERLAY_GUID_WARNING   "{7F256BB6-29D2-4E40-A6C4-E5E756E64C82}" )
set( WIN_MSI_UPGRADE_CODE                "6C9E5670-E8A9-4BBD-9BDF-D003794AC177" )
option( BUILD_WIN_MSI "Build MSI scripts and helper DLL" ON )
