name: IONOS Windows Build
on:
  workflow_dispatch:
  push:
    branches:
      - feature/SES-42_pipeline

defaults:
  run:
    shell: pwsh
jobs:
  build:
    env:
      HOME: ${{ github.workspace }}
      CRAFT_TARGET: windows-msvc2019_64-cl
    name: IONOS Windows Build
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Clone CraftMaster
      run: git clone --depth=1 https://invent.kde.org/kde/craftmaster.git "${{ github.workspace }}\craft\CraftMaster\CraftMaster"

    - name: Craft setup
      run: |
        & "${{ github.workspace }}\.github\workflows\craft_setup.ps1" --setup

    - name: Craft unshelve
      run: |
        & "${{ github.workspace }}\.github\workflows\craft_setup.ps1" -c --unshelve "${{ github.workspace }}\craft.shelf"

    - name: Switch Craft to qt5-lts
      run: |
        & cd "${{ github.workspace }}\craft\CraftMaster\${{ env.CRAFT_TARGET}}\etc\blueprints\locations\craft-blueprints-kde"
        git checkout qt5-lts

    - name: Install dependencies
      run: |
        & "${{ github.workspace }}\.github\workflows\craft_setup.ps1" -c --install-deps nextcloud-client
