name: IONOS Windows Build
on:
  workflow_dispatch:
  push:
    branches:
      - feature/SES-42_pipeline

defaults:
  run:
    shell: pwsh
jobs:
  build:
    env:
      HOME: ${{ github.workspace }}
      CRAFT_TARGET: windows-msvc2019_64-cl
    name: IONOS Windows Build
    runs-on: windows-2019
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Clone CraftMaster
      run: git clone -q --depth=1 https://invent.kde.org/kde/craftmaster.git "${{ github.workspace }}\craft\CraftMaster"

    - name: Craftmaster setup
      run: |
        & "${{ github.workspace }}\.github\workflows\craft_setup.ps1" --setup

    - name: Craft unshelve
      continue-on-error: true
      run: |
        & "${{ github.workspace }}\.github\workflows\craft_setup.ps1" -c --unshelve "${{ github.workspace }}\craft.shelf"

    - name: Install dependencies
      run: |
        & "${{ github.workspace }}\.github\workflows\craft_setup.ps1" -c --install-deps nextcloud-client

    - name: Build
      run: |
        & "${{ github.workspace }}\.github\workflows\craft_setup.ps1" -c --no-cache nextcloud-client